---
pipeline_ex_policy: "seq"
mgrid0: 0.0
mgrid1: 0.0
pixel_size: 1.5
proc.rtc.despike.sigma: 15.0
proc.rtc.samplerate: 64.0
proc.rtc.despike.despikewindow: 65
proc.rtc.despike.timeconstant: 0.015
proc.rtc.filter.flow: 0.0
proc.rtc.filter.fhigh: 8.0
proc.rtc.filter.agibbs: 50.0
proc.rtc.filter.nterms: 32
proc.rtc.downsample.downsamplefactor: 1
proc.ptc.pcaclean.neigToCut: 3
proc.ptc.pcaclean.cutStd: 0.0
proc.rtc.despike: 1
proc.rtc.filter: 1
proc.rtc.downsample: 1 
proc.ptc.cleanpca: 1
noisemaps: 5
iterationcutoff: 0.05
iterationcap: 1
proc.rtc.cores: 1
proc.ptc.cores: 1
proc.map.cores: 1
output_filepath: "/Users/mmccrackan/Documents/toltec/lali_map.nc"

