#!/usr/bin/env python3
"""Regenerate controlled initial-spectrum numbers with the preserved D2 estimator.

This is a test reference, not a scientific profile or a real-data spectrum.
Run with repository root on PYTHONPATH. No legacy line detector is invoked.
"""
from pathlib import Path
import numpy as np
from tools.blank_sky.rtc_line_audit import _masked_welch_psd
from tools.wp7.rtc_filter_psd_line_evidence import _insert_run_separators

CASES=[('even',241,1/16,False,False),('odd',141,4/33,False,False),
       ('padded',241,1/16,True,False),('gapped',241,1/16,False,True)]

def main():
    lines=['// Generated by generate_rtc_native_spectral_reference.py using unchanged D2 helpers.',
           '#pragma once','#include <array>','namespace spectral_reference {']
    for name,n,dt,masked,gapped in CASES:
        i=np.arange(n); t=i*dt
        values=3+.002*i+np.sin(2*np.pi*3*t)+.3*np.cos(2*np.pi*1.2*t)
        values[90]+=7
        times=1000+dt*i
        valid=np.ones(n,dtype=bool)
        if masked:valid[70:80]=False;valid[112:]=False
        runs=np.zeros(n,dtype=int)
        if gapped:runs[120:]=1
        measured_dt=float(np.median(np.diff(times)[runs[1:]==runs[:-1]]))
        centered=values-np.median(values[valid])
        signal,use=_insert_run_separators(centered,valid,runs)
        freq,psd,nwindows=_masked_welch_psd(signal,use,measured_dt,segment_sec=4,min_segment_sec=2,overlap_frac=.5,min_windows=1)
        assert len(freq)==max(16,round(4/measured_dt))//2+1 and nwindows>=2
        lines.append(f'inline constexpr std::size_t {name}_windows = {nwindows};')
        for kind,arr in [('frequency',freq),('psd',psd)]:
            lines.append(f'inline constexpr std::array<double, {len(arr)}> {name}_{kind} = {{')
            lines.extend(f'    {float(v):.17g},' for v in arr)
            lines.append('};')
    lines.append('} // namespace spectral_reference')
    out=Path(__file__).with_name('timestream_rtc_native_spectral_reference.h')
    out.write_text('\n'.join(lines)+'\n')
    print(out)
if __name__=='__main__':main()
