#!/usr/bin/env python3
"""Generate the runtime low-level YAML node allowlist from the leaf contract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml


DEFAULT_MANIFEST = "tools/config/config_leaf_contract_resolved.json"
DEFAULT_OUTPUT = (
    "include/citlali/core/pipeline/config_leaf_schema_generated.h"
)
DEFAULT_CONFIG = "data/config.yaml"


def node_paths(leaf_paths: list[str]) -> list[str]:
    nodes: set[str] = set()
    for leaf_path in leaf_paths:
        current = ""
        for segment in leaf_path.split("."):
            is_sequence = segment.endswith("[]")
            base = segment[:-2] if is_sequence else segment
            current = f"{current}.{base}" if current else base
            nodes.add(current)
            if is_sequence:
                current += "[]"
                nodes.add(current)
    return sorted(nodes)


def yaml_node_paths(value: object, path: str = "") -> set[str]:
    nodes = {path} if path else set()
    if isinstance(value, dict):
        for key, child in value.items():
            child_path = f"{path}.{key}" if path else str(key)
            nodes.update(yaml_node_paths(child, child_path))
    elif isinstance(value, list):
        child_path = path + "[]"
        nodes.add(child_path)
        for child in value:
            nodes.update(yaml_node_paths(child, child_path))
    return nodes


def render(paths: list[str], external_roots: list[str]) -> str:
    values = "\n".join(f'        "{path}",' for path in paths)
    external_values = "\n".join(
        f'        "{path}",' for path in external_roots
    )
    return f"""#pragma once

#include <array>
#include <string_view>

namespace citlali::pipeline {{

// Generated by tools/config/generate_config_schema_header.py.
inline constexpr std::array<std::string_view, {len(paths)}>
    known_low_level_config_node_paths{{{{
{values}
    }}}};

inline constexpr std::array<std::string_view, {len(external_roots)}>
    externally_owned_low_level_config_roots{{{{
{external_values}
    }}}};

}}  // namespace citlali::pipeline
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", default=None)
    parser.add_argument("--manifest", default=DEFAULT_MANIFEST)
    parser.add_argument("--default-config", default=DEFAULT_CONFIG)
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo_root = (
        Path(args.repo_root).resolve()
        if args.repo_root
        else Path(__file__).resolve().parents[2]
    )
    manifest = json.loads((repo_root / args.manifest).read_text())
    leaves = manifest.get("leaves", [])
    paths = set(node_paths([str(row["path"]) for row in leaves]))
    default_config = yaml.safe_load(
        (repo_root / args.default_config).read_text()
    )
    paths.update(yaml_node_paths(default_config))
    paths = sorted(paths)
    external_roots = sorted(
        {
            str(row["path"]).split(".", 1)[0].removesuffix("[]")
            for row in leaves
            if row.get("authority") == "tolteca-observation-inputs"
        }
    )
    content = render(paths, external_roots)
    output = repo_root / args.output
    if args.check:
        if not output.is_file() or output.read_text() != content:
            print(f"runtime config schema header is stale: {output}")
            return 1
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content)
    print(
        "runtime config schema header: "
        f"leaves={len(leaves)} nodes={len(paths)} "
        f"external_roots={len(external_roots)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
