include_guard(GLOBAL)
include(CheckSymbolExists)
check_symbol_exists("shm_open" "sys/mman.h" HAS_SHM)
if (NOT HAS_SHM)
    message("Looking for shm_open in librt")
    find_library(LIBRT_LIBRARIES rt)
    if(NOT LIBRT_LIBRARIES)
        message(FATAL_ERROR "librt not found")
    else()
        message("Found shm_open")
        set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${LIBRT_LIBRARIES}")
    endif()
endif()
