repos:
  toltec.citlali: ../spack_repo/toltec/citlali
  toltec.kidscpp: ../../build/spack-sources/kidscpp/spack_repo/toltec/kidscpp
  toltec.tula: ../../build/spack-sources/tula/spack_repo/toltec/tula
  toltec.tula_cmake: ../../build/spack-sources/tula_cmake/spack_repo/toltec/tula_cmake
