packages:
  gcc:
    externals:
      - spec: gcc@13.3.0 languages:='c,c++'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
    buildable: false

  c:
    require: gcc@13.3.0

  cxx:
    require: gcc@13.3.0
