#pragma once

// Beammap detector fit-QC column ordering helpers.

#include <string>
#include <vector>

namespace beammap_fit_qc_schema {

inline std::vector<std::string> header_keys() {
    return {
        "uid",
        "array",
        "nw",
        "kids_tone",
        "good_fit",
        "converged",
        "converge_iter",
        "flag",
        "flag2",
        "amp",
        "amp_err",
        "cal_amp",
        "cal_amp_method",
        "template_amp",
        "template_offset",
        "template_resid_rms",
        "template_npix",
        "template_amp_over_fit_amp",
        "cal_amp_over_fit_amp",
        "map_peak_amp",
        "map_peak_amp_over_fit_amp",
        "fit_sig2noise",
        "map_rms",
        "map_sig2noise",
        "n_weight_pos",
        "fruitloops_source_x_t",
        "fruitloops_source_y_t",
        "fruitloops_local_sigma",
        "fruitloops_local_sigma_npix",
        "fruitloops_amp_ref",
        "fruitloops_peak_threshold",
        "fruitloops_snr_threshold",
        "fruitloops_adaptive_threshold",
        "fruitloops_support_radius_arcsec",
        "fruitloops_support_npix",
        "fruitloops_support_signal_sum",
        "fruitloops_support_x_span_arcsec",
        "fruitloops_support_y_span_arcsec",
        "rfi_masked_samples",
        "rfi_masked_scans",
        "scan_band_masked_samples",
        "scan_band_masked_rows",
        "scan_band_masked_edge",
        "scan_band_mask_rejected",
        "fit_bound_nhit",
        "fit_bound_code",
        "fit_bound_amp",
        "fit_bound_x",
        "fit_bound_y",
        "fit_bound_a",
        "fit_bound_b",
        "fit_bound_angle",
        "fit_init_amp",
        "fit_init_x_t",
        "fit_init_y_t",
        "fit_init_a_fwhm",
        "fit_init_b_fwhm",
        "fit_low_a_fwhm",
        "fit_high_a_fwhm",
        "fit_low_b_fwhm",
        "fit_high_b_fwhm",
        "prior_init_mode",
        "prior_used",
        "prior_fallback_blind",
        "prior_no_candidate_reason",
        "prior_slot_index",
        "prior_match_d2",
        "prior_match_score",
        "prior_candidate_snr",
        "prior_n_candidates",
        "prior_n_candidates_keep",
        "prior_n_candidates_gate",
        "prior_candidate_x_t_raw",
        "prior_candidate_y_t_raw",
        "prior_candidate_x_t_prior",
        "prior_candidate_y_t_prior",
        "prior_center_x_t",
        "prior_center_y_t",
        "prior_derot_elev",
        "prior_slot_x_t",
        "prior_slot_y_t",
        "prior_slot_sx",
        "prior_slot_sy",
        "final_prior_slot_index",
        "final_prior_d2",
        "x_t_raw",
        "y_t_raw",
        "x_t",
        "y_t",
        "x_t_derot",
        "y_t_derot",
        "a_fwhm",
        "a_fwhm_err",
        "b_fwhm",
        "b_fwhm_err",
        "angle",
        "angle_err",
        "flxscale",
        "sens"
    };
}

} // namespace beammap_fit_qc_schema
