#pragma once

// Beammap detector fit-QC unit and description helpers.

#include <map>
#include <string>

#include <citlali/core/engine/detail/beammap_fit_qc_columns.h>

namespace beammap_fit_qc_schema {

template <class TableAccess>
std::map<std::string, std::string> units(const TableAccess &table_access,
                                         const std::string &sig_unit) {
    return {
        {"uid", "N/A"},
        {"array", "N/A"},
        {"nw", "N/A"},
        {"kids_tone", "N/A"},
        {"good_fit", "N/A"},
        {"converged", "N/A"},
        {"converge_iter", "N/A"},
        {"flag", "N/A"},
        {"flag2", "N/A"},
        {"amp", table_access.unit("amp", sig_unit)},
        {"amp_err", table_access.unit("amp_err", sig_unit)},
        {"cal_amp", table_access.unit("cal_amp", sig_unit)},
        {"cal_amp_method", "N/A"},
        {"template_amp", table_access.unit("template_amp", sig_unit)},
        {"template_offset", table_access.unit("template_offset", sig_unit)},
        {"template_resid_rms", table_access.unit("template_resid_rms", sig_unit)},
        {"template_npix", "pix"},
        {"template_amp_over_fit_amp", "N/A"},
        {"cal_amp_over_fit_amp", "N/A"},
        {"map_peak_amp", table_access.unit("map_peak_amp", sig_unit)},
        {"map_peak_amp_over_fit_amp", "N/A"},
        {"fit_sig2noise", "N/A"},
        {"map_rms", sig_unit},
        {"map_sig2noise", "N/A"},
        {"n_weight_pos", "pix"},
        {"fruitloops_source_x_t", "arcsec"},
        {"fruitloops_source_y_t", "arcsec"},
        {"fruitloops_local_sigma", sig_unit},
        {"fruitloops_local_sigma_npix", "pix"},
        {"fruitloops_amp_ref", sig_unit},
        {"fruitloops_peak_threshold", sig_unit},
        {"fruitloops_snr_threshold", sig_unit},
        {"fruitloops_adaptive_threshold", sig_unit},
        {"fruitloops_support_radius_arcsec", "arcsec"},
        {"fruitloops_support_npix", "pix"},
        {"fruitloops_support_signal_sum", sig_unit},
        {"fruitloops_support_x_span_arcsec", "arcsec"},
        {"fruitloops_support_y_span_arcsec", "arcsec"},
        {"rfi_masked_samples", "samples"},
        {"rfi_masked_scans", "scans"},
        {"scan_band_masked_samples", "samples"},
        {"scan_band_masked_rows", "rows"},
        {"scan_band_masked_edge", "N/A"},
        {"scan_band_mask_rejected", "N/A"},
        {"fit_bound_nhit", "N/A"},
        {"fit_bound_code", "N/A"},
        {"fit_bound_amp", "N/A"},
        {"fit_bound_x", "N/A"},
        {"fit_bound_y", "N/A"},
        {"fit_bound_a", "N/A"},
        {"fit_bound_b", "N/A"},
        {"fit_bound_angle", "N/A"},
        {"fit_init_amp", table_access.unit("amp", sig_unit)},
        {"fit_init_x_t", "arcsec"},
        {"fit_init_y_t", "arcsec"},
        {"fit_init_a_fwhm", "arcsec"},
        {"fit_init_b_fwhm", "arcsec"},
        {"fit_low_a_fwhm", "arcsec"},
        {"fit_high_a_fwhm", "arcsec"},
        {"fit_low_b_fwhm", "arcsec"},
        {"fit_high_b_fwhm", "arcsec"},
        {"prior_init_mode", "N/A"},
        {"prior_used", "N/A"},
        {"prior_fallback_blind", "N/A"},
        {"prior_no_candidate_reason", "N/A"},
        {"prior_slot_index", "N/A"},
        {"prior_match_d2", "N/A"},
        {"prior_match_score", "N/A"},
        {"prior_candidate_snr", "N/A"},
        {"prior_n_candidates", "pix"},
        {"prior_n_candidates_keep", "pix"},
        {"prior_n_candidates_gate", "pix"},
        {"prior_candidate_x_t_raw", "arcsec"},
        {"prior_candidate_y_t_raw", "arcsec"},
        {"prior_candidate_x_t_prior", "arcsec"},
        {"prior_candidate_y_t_prior", "arcsec"},
        {"prior_center_x_t", "arcsec"},
        {"prior_center_y_t", "arcsec"},
        {"prior_derot_elev", "rad"},
        {"prior_slot_x_t", "arcsec"},
        {"prior_slot_y_t", "arcsec"},
        {"prior_slot_sx", "arcsec"},
        {"prior_slot_sy", "arcsec"},
        {"final_prior_slot_index", "N/A"},
        {"final_prior_d2", "N/A"},
        {"x_t_raw", table_access.unit("x_t", "arcsec")},
        {"y_t_raw", table_access.unit("y_t", "arcsec")},
        {"x_t", table_access.unit("x_t", "arcsec")},
        {"y_t", table_access.unit("y_t", "arcsec")},
        {"x_t_derot", table_access.unit("x_t", "arcsec")},
        {"y_t_derot", table_access.unit("y_t", "arcsec")},
        {"a_fwhm", table_access.unit("a_fwhm", "arcsec")},
        {"a_fwhm_err", table_access.unit("a_fwhm_err", "arcsec")},
        {"b_fwhm", table_access.unit("b_fwhm", "arcsec")},
        {"b_fwhm_err", table_access.unit("b_fwhm_err", "arcsec")},
        {"angle", table_access.unit("angle", "rad")},
        {"angle_err", table_access.unit("angle_err", "rad")},
        {"flxscale", table_access.unit("flxscale", "N/A")},
        {"sens", table_access.unit("sens", "N/A")}
    };
}

template <class TableAccess>
std::map<std::string, std::string> descriptions(const TableAccess &table_access) {
    return {
        {"uid", table_access.description("uid", "detector uid")},
        {"array", table_access.description("array", "array index")},
        {"nw", table_access.description("nw", "network index")},
        {"kids_tone", table_access.description("kids_tone", "index of tone in network")},
        {"good_fit", "fit returned a usable solution"},
        {"converged", "beammap iterative convergence flag"},
        {"converge_iter", table_access.description("converge_iter", "beammap convergence iteration")},
        {"flag", table_access.description("flag", "detector quality flag")},
        {"flag2", "bitwise detector quality flag"},
        {"amp", table_access.description("amp", "fitted beam amplitude")},
        {"amp_err", table_access.description("amp_err", "fitted beam amplitude uncertainty")},
        {"cal_amp", table_access.description("cal_amp", "amplitude used for beammap flux calibration")},
        {"cal_amp_method", table_access.description("cal_amp_method", "calibration amplitude method code")},
        {"template_amp", table_access.description("template_amp", "empirical-template matched amplitude")},
        {"template_offset", table_access.description("template_offset", "empirical-template fitted local offset")},
        {"template_resid_rms", table_access.description("template_resid_rms", "empirical-template residual RMS")},
        {"template_npix", table_access.description("template_npix", "number of pixels used by empirical-template amplitude fit")},
        {"template_amp_over_fit_amp", table_access.description("template_amp_over_fit_amp", "empirical-template amplitude divided by Gaussian fit amplitude")},
        {"cal_amp_over_fit_amp", table_access.description("cal_amp_over_fit_amp", "calibration amplitude divided by Gaussian fit amplitude")},
        {"map_peak_amp", table_access.description("map_peak_amp", "local map peak near Gaussian fit center")},
        {"map_peak_amp_over_fit_amp", table_access.description("map_peak_amp_over_fit_amp", "local map peak divided by Gaussian fit amplitude")},
        {"fit_sig2noise", "fitted amplitude divided by fitted amplitude uncertainty"},
        {"map_rms", "standard deviation of positive-weight detector map pixels, excluding fitted source core when possible"},
        {"map_sig2noise", "fitted amplitude divided by support-only detector map rms"},
        {"n_weight_pos", "number of detector-map pixels with positive weight"},
        {"fruitloops_source_x_t", "source-support x center used by adaptive fruit loops feedback"},
        {"fruitloops_source_y_t", "source-support y center used by adaptive fruit loops feedback"},
        {"fruitloops_local_sigma", "local annulus robust sigma used by adaptive fruit loops feedback"},
        {"fruitloops_local_sigma_npix", "number of local-annulus pixels used for fruit loops local sigma"},
        {"fruitloops_amp_ref", "amplitude reference used by adaptive fruit loops feedback"},
        {"fruitloops_peak_threshold", "peak-fraction threshold component for adaptive fruit loops feedback"},
        {"fruitloops_snr_threshold", "local-S/N threshold component for adaptive fruit loops feedback"},
        {"fruitloops_adaptive_threshold", "final adaptive threshold used for fruit loops map feedback"},
        {"fruitloops_support_radius_arcsec", "radial source-support limit used by adaptive fruit loops feedback"},
        {"fruitloops_support_npix", "number of final-map positive-weight pixels passing adaptive fruit loops threshold and support cuts"},
        {"fruitloops_support_signal_sum", "sum of final-map signal over pixels passing adaptive fruit loops threshold and support cuts"},
        {"fruitloops_support_x_span_arcsec", "x span of final-map pixels passing adaptive fruit loops threshold and support cuts"},
        {"fruitloops_support_y_span_arcsec", "y span of final-map pixels passing adaptive fruit loops threshold and support cuts"},
        {"rfi_masked_samples", "number of timestream samples masked by beammap rfi_mask"},
        {"rfi_masked_scans", "number of scans with at least one sample masked by beammap rfi_mask"},
        {"scan_band_masked_samples", "number of timestream samples masked by beammap scan_band_mask"},
        {"scan_band_masked_rows", "number of detector-map edge rows flagged by beammap scan_band_mask"},
        {"scan_band_masked_edge", "scan-band edge code (0 none, 1 top, 2 bottom, 3 both)"},
        {"scan_band_mask_rejected", "1 if scan_band_mask proposed a mask but rejected it due to max_flagged_fraction"},
        {"fit_bound_nhit", "number of fitted parameters at lower/upper bounds"},
        {"fit_bound_code", "bitmask of bound-hit parameters (see metadata legend)"},
        {"fit_bound_amp", "bound state for amplitude (-1 lower, 0 none, +1 upper)"},
        {"fit_bound_x", "bound state for fitted x center (-1 lower, 0 none, +1 upper)"},
        {"fit_bound_y", "bound state for fitted y center (-1 lower, 0 none, +1 upper)"},
        {"fit_bound_a", "bound state for fitted a sigma/FWHM (-1 lower, 0 none, +1 upper)"},
        {"fit_bound_b", "bound state for fitted b sigma/FWHM (-1 lower, 0 none, +1 upper)"},
        {"fit_bound_angle", "bound state for fitted angle (-1 lower, 0 none, +1 upper)"},
        {"fit_init_amp", "initial amplitude used by Gaussian fitter"},
        {"fit_init_x_t", "initial x position converted to arcsec offset"},
        {"fit_init_y_t", "initial y position converted to arcsec offset"},
        {"fit_init_a_fwhm", "initial a FWHM implied by fitter initialization"},
        {"fit_init_b_fwhm", "initial b FWHM implied by fitter initialization"},
        {"fit_low_a_fwhm", "active lower bound for a FWHM"},
        {"fit_high_a_fwhm", "active upper bound for a FWHM"},
        {"fit_low_b_fwhm", "active lower bound for b FWHM"},
        {"fit_high_b_fwhm", "active upper bound for b FWHM"},
        {"prior_init_mode", "prior-init mode code (0 blind, 1 previous, 2 prior, -1 skipped/not fit)"},
        {"prior_used", "1 if the final initialization seed came from priors, else 0"},
        {"prior_fallback_blind", "1 if priors were attempted but blind fallback was used, else 0"},
        {"prior_no_candidate_reason", "reason code when priors produced no accepted candidate (see metadata legend)"},
        {"prior_slot_index", "matched prior slot index for the chosen prior-guided seed"},
        {"prior_match_d2", "Mahalanobis d^2 of chosen prior-guided seed in prior frame"},
        {"prior_match_score", "prior ranking score of chosen prior-guided seed"},
        {"prior_candidate_snr", "S/N metric of chosen prior-guided seed candidate"},
        {"prior_n_candidates", "number of weighted pixels above prior min_snr before top-N truncation"},
        {"prior_n_candidates_keep", "number of top-ranked candidates retained for prior scoring"},
        {"prior_n_candidates_gate", "number of retained candidates that passed the prior d^2 gate"},
        {"prior_candidate_x_t_raw", "chosen prior-guided candidate x offset before prior-frame transforms"},
        {"prior_candidate_y_t_raw", "chosen prior-guided candidate y offset before prior-frame transforms"},
        {"prior_candidate_x_t_prior", "chosen prior-guided candidate x offset in the prior frame"},
        {"prior_candidate_y_t_prior", "chosen prior-guided candidate y offset in the prior frame"},
        {"prior_center_x_t", "array-center x offset subtracted before prior matching"},
        {"prior_center_y_t", "array-center y offset subtracted before prior matching"},
        {"prior_derot_elev", "derotation elevation used for prior-frame matching"},
        {"prior_slot_x_t", "matched prior slot x center in the prior frame"},
        {"prior_slot_y_t", "matched prior slot y center in the prior frame"},
        {"prior_slot_sx", "matched prior slot soft x sigma"},
        {"prior_slot_sy", "matched prior slot soft y sigma"},
        {"final_prior_slot_index", "nearest prior slot index for final detector position in the prior frame"},
        {"final_prior_d2", "nearest-slot Mahalanobis d^2 for final detector position in the soft-prior frame"},
        {"x_t_raw", "raw x position before reference subtraction/derotation"},
        {"y_t_raw", "raw y position before reference subtraction/derotation"},
        {"x_t", table_access.description("x_t", "detector x position")},
        {"y_t", table_access.description("y_t", "detector y position")},
        {"x_t_derot", "detector x position after derotation transform"},
        {"y_t_derot", "detector y position after derotation transform"},
        {"a_fwhm", table_access.description("a_fwhm", "fitted major-axis FWHM")},
        {"a_fwhm_err", table_access.description("a_fwhm_err", "fitted major-axis FWHM uncertainty")},
        {"b_fwhm", table_access.description("b_fwhm", "fitted minor-axis FWHM")},
        {"b_fwhm_err", table_access.description("b_fwhm_err", "fitted minor-axis FWHM uncertainty")},
        {"angle", table_access.description("angle", "fitted beam angle")},
        {"angle_err", table_access.description("angle_err", "fitted beam angle uncertainty")},
        {"flxscale", table_access.description("flxscale", "flux conversion factor")},
        {"sens", table_access.description("sens", "detector sensitivity")}
    };
}

} // namespace beammap_fit_qc_schema
